services:
  postgres:
    image: postgres:17-alpine
    container_name: food-hub-postgres
    restart: unless-stopped
    environment:
      POSTGRES_USER: foodhub
      POSTGRES_PASSWORD: foodhub
      POSTGRES_DB: foodhub
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
